Controllers films users
Dimka-pixel/java-filmorate pull request #3
Opened 2023-04-30 09:30 UTC by Dimka-pixel

2023-04-30 19:54 UTC, Dimka-pixel commented
first pull request comment

2023-05-01 20:18 UTC, TarasovSam requested changes
Дмитрий, привет!
Проверил твое задание, спасибо за работу. Отдельно хочу отметить логирование не только ошибок/исключений, но и удачных попыток (так логи будут отображать полную историю действий). Оставил комментарии с тем, что можно улучшить и что нужно поправить (основное - это перенести всю логику из контроллера в сервис и тесты), плюс пару вопросов)
Жду твою работу на следующую итерацию!) Если будут вопросы, пиши в пачку)

2023-05-01 20:18 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
Можно было бы избавиться от большинства проверок валидации в коде и реализовать их с помощью аннотаций)
Например, над описанием можно было бы использовать @SiZe.
Для продолжительности @positive или @min(1), чтобы запретить передавать отрицательное значение.
Чтобы эти аннотации стали учитываться, следует добавить перед параметром Film film, в методах создания и обновления, аннотацию @Valid. Аналогично и с пользователем)
Кстати, тесты для валидации, которая реализована с помощью аннотаций писать необязательно.

2023-05-01 20:18 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final String name;
А почему решил почти для всех полей прописать final?

2023-05-01 20:18 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final String login;
Для валидации логина было бы очень удобно использовать @pattern в связке с @notblank
https://www.geeksforgeeks.org/spring-mvc-regular-expression-validation/

2023-05-01 20:18 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final LocalDate birthday;
А если день рождения сегодня?)

2023-05-01 20:18 UTC, TarasovSam commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
А где тесты?)

2023-05-03 19:08 UTC, Dimka-pixel commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final String name;
Чтобы объекты были максимально не изменяемыми, чтобы с данными ничего не случилось

2023-05-03 19:09 UTC, Dimka-pixel commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
@positive или @min(1) не подходят для типа Duration, поэтому реализовал проверку в  сервисе

2023-05-04 19:37 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/Cotroller/FilmController.java
> +    public List<Film> getFilms() {
Замечание о переносе всей реализации логики методов из контроллера в сервиса не исправлено.
Т.е. должно получиться что-то вроде такого:
 @GetMapping("/films")
public List<Film> getFilms() {
        filmService.getFilms();
}

2023-05-04 19:42 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/Cotroller/UserController.java
>          List<User> usersList = new ArrayList<User>(users.values());
Здесь тоже самое. Создай сервис UserService и перенеси всю логику туда

2023-05-04 19:44 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/ObjectMapperConfiguration.java
Лишняя пустая строка, замечал ее и в других местах
Чтобы не отлавливать руками такие вещи (плюс всякие отступы и пробелы), используй комбинацию Ctrl+Alt+L

2023-05-04 19:46 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/Validation/FilmValidator.java
> +        } else if (film.getDuration().toMinutes() <= 0) {
Если duration=null у переданного фильма, что будет?
И почему не захотел использовать аннотацию для валидации продолжительности?

2023-05-04 19:46 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/Validation/FilmValidator.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Если releaseDate=null у переданного фильма, что будет?

2023-05-04 19:47 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/Validation/UserValidator.java
> +        if (user.getName() == null) {
Если name="    ", валидацию пользователь пройдет?

2023-05-04 19:49 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final String name;
Ну допустим, что так. Но получается, что в процессе мы не сможем поменять, например, описание фильма. Или первоначально ошиблись с продолжительностью и все, так фильм с неправильной продолжительностью и будет. Это удобно, как думаешь?

А для пользователя уже никогда нельзя будет поменять почту или имя. Потерял доступ к почте, с которой регистрировался - до свидания))

2023-05-04 19:54 UTC, TarasovSam commented on src/test/java/ru/yandex/practicum/filmorate/Validation/FilmValidatorTest.java
> +    private FilmValidator validator;
Создай хотя бы еще один фильм, который проходит валидацию)

2023-05-04 19:55 UTC, TarasovSam commented on src/test/java/ru/yandex/practicum/filmorate/Validation/UserValidatorTest.java
> +    private UserValidator validator;
А здесь добавь пользователя, который не проходит))

2023-05-06 11:52 UTC, Dimka-pixel commented
Перенёс всю логику в service
Добавил тесты
использование final считаю допустимым, поскольку со стороны пользователя есть функция update, для исправления. Если это критичная ошибка или от этого будет зависеть дальнейшая логика, напиши я поменяю
Аннотацию @Positive не использую поскольку возникает конфликт с типом данных Duration
По поводу codestyle:
Я перед от правкой вроде всё перепроверяю и использую Ctrl+Alt+L и Ctrl+Alt+O, но почему-то иногда всё равно  появляются не использованные импорты и пустые строки

2023-05-06 17:38 UTC, TarasovSam reviewed
Дмитрий, спасибо за работу и ответы. Оставил еще несколько комментариев (обязательно проработай их  в части модификаторов, аннотаций и проверок).
Задание я принимаю (доработки внеси перед следующим спринтом, их совсем чуть осталось), успеха в обучении и до следующего спринта!) Если будут вопросы, пиши в пачку.
На счет модификатора final для полей сущности. Update не поможет, потому что поля ты зафинализировал - сделал их неизменяемыми после создания и присвоения.  Я бы убрал эти модификаторы, хотя сейчас это не критичная ошибка, т.к. используется обычный класс. А вот в дальнейшем при использовании JPA с этим будут проблемы)

2023-05-06 17:38 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/cotroller/FilmController.java
> +    private FilmServiceManager manager;
Следует прописать модификатор final

2023-05-06 17:38 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/cotroller/UserController.java
> +    private UserServiceManager manager;
Следует прописать модификатор final

2023-05-06 17:38 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NonNull
Согласно ТЗ для Film:
- название не может быть пустым (тут аннотация нужна);
- максимальная длина описания — 200 символов (тут же описание может быть пустым, т.е. его просто не написали);
- дата релиза — не раньше 28 декабря 1895 года (здесь тоже дата релиза может отсутствовать);
- продолжительность фильма должна быть положительной (и здесь тоже).

Поэтому убери аннотации для полей releaseDate и duration

2023-05-06 17:38 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceManager.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Т.к. аннотация над полем уберется, то здесь необходима проверка на null, чтобы не поймать npe
film.getReleaseDate() != null

2023-05-06 17:38 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceManager.java
> +        } else if (film.getDuration().toMinutes() <= 0) {
Тут тоже необходима проверка на null, чтобы не поймать npe

2023-05-06 17:38 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceManager.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Проверка isBlank() включает в себя проверку на null, нет необходимости в двойной проверке

2023-05-06 17:38 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceManager.java
> +        } else if (user.getName() == null || user.getName().isBlank()) {
Тут тоже

2023-05-06 17:38 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceManager.java
> +        } else if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Здесь и в 47 строке тоже

2023-05-14 07:12 UTC, closed without merging